#!/bin/bash
shopt -s extglob

# unset D_USE_FREELISTS for best valgrind results
# setenv VALGRIND 'valgrind -q '
VALGRIND=

cp Makefile *.c *.h grammar.g tests
cd tests
make -s make_dparser
make gram
make -s make_dparser
failed=0
grammars=*.test.g
for g in $grammars ; do
  rm -f sample_parser
  if [ -f "$g.flags" ] ; then
    flags=$(cat $g.flags)
  else
    flags=
  fi
  $VALGRIND ./make_dparser $flags $g
  make -s sample_parser SAMPLE_GRAMMAR=$(basename $g)
  files="$g."+([0-9])
  for t in $files ; do
    if test -f "$t.flags" ; then
      flags=$(cat $t.flags)
    else
      flags=
    fi
    $VALGRIND ./sample_parser $flags -v $t &> $t.out
    diff $t.out $t.check
    result=$?
    if [ $result -ne 0 ]; then
      echo $t "******** FAILED ********"
      failed=$((failed + 1))
    else
      echo $t "PASSED"
    fi
  done
done
echo "---------------------------------------"
if [ $failed -eq 0 ] ; then
  echo "ALL tests PASSED"
else
  echo "********" $failed "test(s) FAILED *********"
fi
rm -f sample_parser D_BUILD_VERSION Makefile *.c *.h *.o make_dparser libdparse.a grammar.g
cd ..
