[package]
name = "example"
version = "0.1.0"
edition = "2024"
publish = false

build = "build.rs"

[dependencies]
dparser_lib = { path = "../dparser_lib" }

[build-dependencies]
dparser_lib = { path = "../dparser_lib" }
cc = "1.0"
