//! `tables.rs`
//! Native Rust implementation of `read_binary.c`. Given a raw memory buffer of `dparser.bin` 
//! generated by `write_binary_tables`, it safely applies relocations internally and 
//! yields a boxed/static reference to the deeply nested `D_ParserTables`.

use crate::bindings::{D_ParserTables, D_ReductionCode};
use std::ffi::c_void;

#[repr(C)]
struct BinaryTablesHead {
    n_relocs: i32,
    n_strings: i32,
    d_parser_tables_loc: i32,
    tables_size: i32,
    strings_size: i32,
}

pub struct BinaryTables<'a> {
    pub parser_tables_gram: &'a mut D_ParserTables,
    _buffer: Vec<u8>,
}

pub fn load_binary_tables<'a>(
    data: &[u8],
    spec_code: D_ReductionCode,
    final_code: D_ReductionCode,
) -> Result<BinaryTables<'a>, &'static str> {
    if data.len() < std::mem::size_of::<BinaryTablesHead>() {
        return Err("Binary tables file too small");
    }

    let mut offset = 0;
    
    // Read Header
    let head_size = std::mem::size_of::<BinaryTablesHead>();
    let head = unsafe { &*(data[offset..offset + head_size].as_ptr() as *const BinaryTablesHead) };
    offset += head_size;

    // Buffer to hold relocated memory natively without touching pure static lifetime limits
    let mut buffer = data[offset..].to_vec();
    if buffer.len() < (head.tables_size + head.strings_size) as usize {
        return Err("Binary tables data truncated");
    }

    let tables_buf_start = buffer.as_mut_ptr() as usize;
    let strings_buf_start = tables_buf_start + head.tables_size as usize;

    let mut str_ptr = offset + (head.tables_size + head.strings_size) as usize;

    // Apply Relocations (n_relocs)
    for _ in 0..head.n_relocs {
        if str_ptr + std::mem::size_of::<usize>() > data.len() {
            return Err("Invalid relocation offset mapping bounds"); 
        }
        
        let reloc_offset = unsafe { *(data[str_ptr..].as_ptr() as *const isize) };
        str_ptr += std::mem::size_of::<isize>();
        
        if reloc_offset < 0 || reloc_offset as usize + std::mem::size_of::<*mut c_void>() > head.tables_size as usize {
            return Err("Relocation offset out of bounds");
        }

        let ptr_addr = tables_buf_start + reloc_offset as usize;
        unsafe {
            let intptr = &mut *(ptr_addr as *mut isize);
            match *intptr {
                -1 => *intptr = 0,
                -2 => *intptr = std::mem::transmute::<_, isize>(spec_code),
                -3 => *intptr = std::mem::transmute::<_, isize>(final_code),
                val => *intptr = val + tables_buf_start as isize,
            }
        }
    }

    // Apply String Relocations
    for _ in 0..head.n_strings {
        if str_ptr + std::mem::size_of::<isize>() > data.len() {
            return Err("Invalid string relocation offset mapping bounds");
        }
        
        let reloc_offset = unsafe { *(data[str_ptr..].as_ptr() as *const isize) };
        str_ptr += std::mem::size_of::<isize>();
        
        if reloc_offset < 0 || reloc_offset as usize + std::mem::size_of::<*mut c_void>() > head.tables_size as usize {
            return Err("String relocation offset out of bounds");
        }

        let ptr_addr = tables_buf_start + reloc_offset as usize;
        unsafe {
            let intptr = &mut *(ptr_addr as *mut isize);
            *intptr += strings_buf_start as isize;
        }
    }

    if head.d_parser_tables_loc < 0 || head.d_parser_tables_loc as usize + std::mem::size_of::<D_ParserTables>() > head.tables_size as usize {
        return Err("Invalid d_parser_tables_loc from root binary mapping");
    }

    let p_tables_address = tables_buf_start + head.d_parser_tables_loc as usize;
    let parser_tables_gram = unsafe { &mut *(p_tables_address as *mut D_ParserTables) };

    Ok(BinaryTables {
        parser_tables_gram,
        _buffer: buffer,
    })
}
